[tool.poetry]
name = "debugroll"
version = "0.0.1"
description = ""
authors = []
packages = [
  { include = "debugroll" }
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^8.0.0"
taskipy = "^1.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
test = "pytest"
